var THESAURUS = {
	three: ["a", "b", "c", "d", "e", "f", "g", "h","i", "j", "k", "l", "m", "o", "p", "q", "r", "t", "u", "v", "w", "y", 
	"z"],
	small: ["aa", "ab", "ac", "ad", "ae", "af", "ag", "ah", "ai", "aj", "ak", "al", "am", "an", "ao", "ap", "aq", "ar", 
	"as", "at", "au", "av", "aw", "ax", "ay", "az", "ba", "bb", "bc", "bd", "be", "bf", "bg", "bh", "bi", "bj", "bk", 
	"bl", "bm", "bn", "bo", "bp", "bq", "br", "bs", "bt", "bu", "bv", "bw", "bx", "by", "bz", "ca", "cb", "cc", "cd", 
	"ce", "cf", "cg", "ch", "ci", "cj", "ck", "cl", "cm", "cn", "co", "cp", "cq", "cr", "cs", "ct", "cu", "cv", "cw", 
	"cx", "cy", "cz", "da", "db", "dc", "dd", "de", "df", "dg", "dh", "di", "dj", "dk", "dl", "dm", "dn", "do", "dp", 
	"dq", "dr", "ds", "dt", "du", "dv", "dw", "dx", "dy", "dz", "ea", "eb", "ec", "ed", "ee", "ef", "eg", "eh", "ei", 
	"ej", "ek", "el", "em", "en", "eo", "ep", "eq", "er", "es", "et", "eu", "ev", "ew", "ex", "ey", "ez", "fa", "fb", 
	"fc", "fd", "fe", "ff", "fg", "fh", "fi", "fj", "fk", "fl", "fm", "fn", "fo", "fp", "fq", "fr", "fs", "ft", "fu", 
	"fv", "fw", "fx", "fy", "fz", "ga", "gb", "gc", "gd", "ge", "gf", "gg", "gh", "gi", "gj", "gk", "gl", "gm", "gn", 
	"go", "gp", "gq", "gr", "gs", "gt", "gu", "gv", "gw", "gx", "gy", "gz", "ha", "hb", "hc", "hd", "he", "hf", "hg", 
	"hh", "hi", "hj", "hk", "hl", "hm", "hn", "ho", "hp", "hq", "hr", "hs", "ht", "hu", "hv", "hw", "hx", "hy", "hz", 
	"ia", "ib", "ic", "id", "ie", "if", "ig", "ih", "ii", "ij", "ik", "il", "im", "in", "io", "ip", "iq", "ir", "is", 
	"it", "iu", "iv", "iw", "ix", "iy", "iz", "ja", "jb", "jc", "jd", "je", "jf", "jg", "jh", "ji", "jj", "jk", "jl", 
	"jm", "jn", "jo", "jp", "jq", "jr", "js", "jt", "ju", "jv", "jw", "jx", "jy", "jz", "ka", "kb", "kc", "kd", "ke", 
	"kf", "kg", "kh", "ki", "kj", "kk", "kl", "km", "kn", "ko", "kp", "kq", "kr", "ks", "kt", "ku", "kv", "kw", "kx", 
	"ky", "kz", "la", "lb", "lc", "ld", "le", "lf", "lg", "lh", "li", "lj", "lk", "ll", "lm", "ln", "lo", "lp", "lq", 
	"lr", "ls", "lt", "lu", "lv", "lw", "lx", "ly", "lz", "ma", "mb", "mc", "md", "me", "mf", "mg", "mh", "mi", "mj", 
	"mk", "ml", "mm", "mn", "mo", "mp", "mq", "mr", "ms", "mt", "mu", "mv", "mw", "mx", "my", "mz", "na", "nb", "nc", 
	"nd", "ne", "nf", "ng", "nh", "ni", "nj", "nk", "nl", "nm", "nn", "no", "np", "nq", "nr", "ns", "nt", "nu", "nv", 
	"nw", "nx", "ny", "nz", "oa", "ob", "oc", "od", "oe", "of", "og", "oh", "oi", "oj", "ok", "ol", "om", "on", "oo", 
	"op", "oq", "or", "os", "ot", "ou", "ov", "ow", "ox", "oy", "oz", "pa", "pb", "pc", "pd", "pe", "pf", "pg", "ph", 
	"pi", "pj", "pk", "pl", "pm", "pn", "po", "pp", "pq", "pr", "ps", "pt", "pu", "pv", "pw", "px", "py", "pz", "qa", 
	"qb", "qc", "qd", "qe", "qf", "qg", "qh", "qi", "qj", "qk", "ql", "qm", "qn", "qo", "qp", "qq", "qr", "qs", "qt", 
	"qu", "qv", "qw", "qx", "qy", "qz", "ra", "rb", "rc", "rd", "re", "rf", "rg", "rh", "ri", "rj", "rk", "rl", "rm", 
	"rn", "ro", "rp", "rq", "rr", "rs", "rt", "ru", "rv", "rw", "rx", "ry", "rz", "sa", "sb", "sc", "sd", "se", "sf", 
	"sg", "sh", "si", "sj", "sk", "sl", "sm", "sn", "so", "sp", "sq", "sr", "ss", "st", "su", "sv", "sw", "sx", "sy", 
	"sz", "ta", "tb", "tc", "td", "te", "tf", "tg", "th", "ti", "tj", "tk", "tl", "tm", "tn", "to", "tp", "tq", "tr", 
	"ts", "tt", "tu", "tv", "tw", "tx", "ty", "tz", "ua", "ub", "uc", "ud", "ue", "uf", "ug", "uh", "ui", "uj", "uk", 
	"ul", "um", "un", "uo", "up", "uq", "ur", "us", "ut", "uu", "uv", "uw", "ux", "uy", "uz", "va", "vb", "vc", "vd", 
	"ve", "vf", "vg", "vh", "vi", "vj", "vk", "vl", "vm", "vn", "vo", "vp", "vq", "vr", "vs", "vt", "vu", "vv", "vw", 
	"vx", "vy", "vz", "wa", "wb", "wc", "wd", "we", "wf", "wg", "wh", "wi", "wj", "wk", "wl", "wm", "wn", "wo", "wp", 
	"wq", "wr", "ws", "wt", "wu", "wv", "ww", "wx", "wy", "wz", "xa", "xb", "xc", "xd", "xe", "xf", "xg", "xh", "xi", 
	"xj", "xk", "xl", "xm", "xn", "xo", "xp", "xq", "xr", "xs", "xt", "xu", "xv", "xw", "xx", "xy", "xz", "ya", "yb", 
	"yc", "yd", "ye", "yf", "yg", "yh", "yi", "yj", "yk", "yl", "ym", "yn", "yo", "yp", "yq", "yr", "ys", "yt", "yu", 
	"yv", "yw", "yx", "yy", "yz", "za", "zb", "zc", "zd", "ze", "zf", "zg", "zh", "zi", "zj", "zk", "zl", "zm", "zn", 
	"zo", "zp", "zq", "zr", "zs", "zt", "zu", "zv", "zw", "zx", "zy", "zz"],
	medium: ["word", "typing", "hi", "good", "how", "are", "you", "welcome", "job", "hop", "hello", "bye", "morning", 
	"kiwi", "berry", "tom", "jerry", "bot", "pot", "cook", "hint", "mint", "mine", "my", "you", "your", "huh", "why",
    "ant", "bird", "worm", "snake", "chat", "wind", "windy", "hot", "hotter", "hottest", "cold", "cool", "apple", "win",
    "won", "kind", "king", "kick", "catch", "cat", "dog", "duck", "chicken", "winner", "woa", "wheel", "with", "love",
    "like", "lone", "alone", "lovely", "hate", "prefer", "hope", "old", "age", "agent", "adult", "one", "two", "three",
    "four", "five", "six", "seven", "eight", "nine", "ten", "teen", "eleven", "twin", "double", "hundred", "move", "go",
    "gone", "give", "given", "rain", "rainbow", "boat", "bite", "cow", "count", "document", "crocked","gullies","oxidizes",
	"inspects","atrocity","elation","leered","khalifs","unpacked","jaunts","inactive","seraphim","canyon","comperes",
	"pertains","spinneys","fatter","trimmer","scrolls","cadgers","onions","freehold","voltages","caviare","cringes",
	"genetics","topping","therms","pastures","upturned","drifter","exiles","titters","zooming","execute","borscht",
	"seafront","meanies","uncurls","mislead","twinset","razzed","airing","punter","boules","tunics","gangly","coccyx",
	"cheddar","ridded","oldies","cabinet","adieus","briers","reopen","cashiers","risottos","screeds","ushers","naffest",
	"hellos","sappier","phoniest","weather","cheerily","felonies","fagged","defied","antennas","rubella","remand",
	"litigant","busting","throat","trialed","shindigs","lunched","tectonic","donkey","topees","hoarding","whereof",
	"complied","felons","futile","monolith","defaced","trusted","hacker","masthead","valuer","taverns","demobs","whined",
	"scuttles","collided","strife","marque","preppies","worsen","errands","imparted","infusion","twelves","solves",
	"beaded","reigned","rattled","empire","fouling","carrel","impetus","plaque","dyslexia","instinct","dimwits","shrewd",
	"murder","shiner","precook","magpies","happens","endeared","chippy","glares","wrongs","beggars","spayed","cutouts",
	"migrated","uneasier","regimes","slurred","loudest","prodigy","oilier","sizzler","ampules","region","roadies",
	"peahens","gazumped","rappers","valency","voided","cesspit","phonier","curios","getaways","piffle","cornrows",
	"thinking","flashgun","hoaxing","spectrum","falconry","decisive","airspace","carpet","creaking","whorls","welled",
	"curtseys","pushcart","vitiate","forwent","colluded","tramps","shuteye","buried","charmers","thruway","terrapin",
	"solvency","unveiled","scourers","abjectly","islander","befallen","overdid","federal","surely","resell","crusade",
	"manured","dabbles","fleshed","noblest","guiding","influx","minuting","clangor","heroism","speech","beaters","rubies",
	"mezzos","sheared","caught","whingers","reactant","medicos","messiah","yarmulke","supreme","ponied","majesty",
	"scheming","clayey","pickers","trouble","proctors","deposes","clarity","aright","entrant","renowned","yakking",
	"rodeos","aphasia","heaters","lankier","royalty","bargain","missile","seventh","rudeness","calyxes","raggedly",
	"manners","enchants","datebook","overuse","truisms","saviour","grandads","punished","backside","breaking","babies",
	"thrush","powdery","prances","truancy","realises","flubbed","patrols","stumped","smirks","injured","sabres","felling",
	"condos","poplar","vocation","terror","risking","aeration","horned","utilises","humanly","confess","roundest",
	"tingling","aldermen","blossom","normalcy","lodger","larked","prompt","bomber","artisans","allayed","subsumes",
	"divisors","inflates","creels","loveys","prefixed","engaging","biscuits","surgeons","legates","sunburnt","sunders",
	"teller","pensions","relaying","diagrams","caresses","cygnets","creeds","mutates","octave","begets","purled","posses",
	"tawdrier","sirloins","anyhow","attract","doorbell","adepts","ingest","cathodes","outrider","cogency","scuttled",
	"plates","managing","puppetry","diluting","relieve","peacocks","condors","scouring","hammock","scabbard","convict",
	"heinous","trousers","dandling","history","disliked","narrows","gracing","driest","dearly","ovation","database",
	"amicable","infidel","osprey","ravages","abased","eminent","rundowns","medico","boarder","clappers","kidnaped",
	"flutters","hurtles","confined","deprived","crucify","marveled","revered","defrays","elitists","assessed","upbraids",
	"goggling","smudgier","spotter","spenders","hornpipe","muzzled","yawing","maracas","busload","webbing","somberly",
	"teaming","princess","internee","emeritus","sloping","streak","scuttle","bilious","attempt","gabbled","boasting",
	"outdoor","captures","jasmines","crappier","reposing","abdomen","foresee","convicts","invent","muzzles","pageboys",
	"pendulum","crazies","savoys","sneers","cleaned","shippers","ionize","degrade","noughts","disturbs","damaged",
	"fanzines","curses","monarchy","applied","prangs","intrigue","grands","genial","decipher","skittles","nunnery",
	"gestalts","bosomy","runner","mindset","channels","resists","sideline","monolog","keeping","manifold","quacking",
	"frighten","interact","bedpan","teamed","beckoned","rowers","cumulus","apprise","vessel","hearths","analogue",
	"gorgeous","terribly","surround","chessman","stouter","chorale","betrays","bustiers","romping","complies","itemizes",
	"harvests","craning","toilets","assisted","biopics","tardily","fusspots","elliptic","fatherly","opaque","tousled",
	"viewer","newscast","proven","debris","blanks","erection","fetching","sculpt","canting","exhale","motoring",
	"syndrome","hearts","washes","cement","fussily","reforms","elusive","campaign","citadels","validly","casual",
	"skiing","ballots","freezers","emetics","swimwear","piddle","advocate","deluded","clawed","taxable","pinged",
	"pierce","borehole","misled","ripcords","plummet","regard","reefed","humorist","decoyed","weevil","skittish",
	"cowslips","distant","gloved","cuddlier","porosity","busses","concurs","editor","plectrum","laburnum","eugenics",
	"beetle","matron","hassling","locust","shogun","launders","gamiest","medicine","wittily","quartos","caress","incline",
	"peddling","besting","ponchos","rigidly","tombolas","perjured","stemmed","shared","cantons","emulate","acclaim",
	"showboat","suspend","fanfare","nerved","activist","legible","ottomans","smelts","morons","perisher","bashful",
	"turbots","turtle","blithely","birdies","citing","animator","emigrate","gobbing","tanning","dweller","tasking",
	"potties","prised","bobbin","livening","clangs","rambling","famines","eggshell","preying","echelons","acting",
	"tiptoe","partial","beading","pastrami","quayside","lodestar","staples","rhapsody","gigging","families","offered",
	"fraught","andantes","sashes","ornery","stresses","landed","driving","outbreak","battered","jaywalk","petition",
	"libels","servants","registry","downcast","boldly","wisteria","dreamily","bounced","reveals","furrows","deckhand",
	"weapon","louvers","bedpost","debuts","valleys","readied","buoyed","grandad","chemise","bootlegs","endears",
	"turnpike","quintets","temple","barges","origami","mandrake","steppe","unjustly","repress","loathing","mincer",
	"dredger","cruelly","battle","harshest","atolls","smashed","pictured","derisory","snuffled","cleaved","victor",
	"talking","deform","withheld","subsume","dictums","shaikhs","shortcut","blokes","catalogs","ditching","decamped",
	"outlooks","arcane","taffeta","misspelt","opaquely"],
	big: ["picnicked","admonitions","exculpate","hospitably","voracious","punctuation","ludicrous","enormously",
	"qualifying","dislocates","knockouts","campaniles","broadswords","demoniacal","generalists","parentheses",
	"infantrymen","phonetician","labelling","forgetting","sobriquets","outweighing","intimations","spacewalks",
	"depressant","paralyzes","combating","goalposts","shoemaker","hardcover","chemically","strategies","exuberantly",
	"daydreams","pluperfect","weeknight", "salivated","repenting","inquiringly","immorally",
	"bandleaders","scallywags","expectorate","timeservers","reminders","catalogue","termination","blancmange","besieging",
	"sportswear","realization","virulence","tragically","floggings","vibraphone"],
	large: ["straightening","deregulating","unilaterally","restructurings","chairpersons","increasingly",
	"pterodactyls","fascinatingly","prizefighter","appertaining","encouragements","reconnoitres","guardianship",
	"acquaintance","summerhouses","resemblances","egocentrically","probabilities","breathalyzing","scorekeepers",
	"millionairess"]
};